### ISSUE TITLE
tar --xattrs only works on centos

### ISSUE THREAD

**Issue by oliveagle** [jwilder/docker-squash#10]
I'm trying to use `docker-squash` within `google/golang` images. but got this error message.  

```
root@d9598f24a46c:/gopath# docker save ce4190a0e33a | bin_debian7/docker-squash -t squash | docker load
tar: unrecognized option '--xattrs'
Try `tar --help' or `tar --usage' for more information.
ERROR: exit status 64
2014/11/11 07:59:16 Error: EOF
```

tar `--xattrs` seems only works on CentOS. both debian7 and max 10.9 don't support this option. 

utils.go

```
17  cmd := exec.Command("tar", "--same-owner", "--xattrs", "--overwrite",
18          "--preserve-permissions", "-xf", src, "-C", dest)
```

centos6

```
$ cat /etc/centos-release 
CentOS release 6.6 (Final)
root ~ [8:44:57]
$ tar --help | grep xattrs
      --no-xattrs            Don't extract the user/root xattrs from the
      --xattrs               Save the user/root xattrs to the archive
```

google/golang

```
root@d9598f24a46c:/gopath# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
root@d9598f24a46c:/gopath# tar --help | grep xattrs
root@d9598f24a46c:/gopath# 
```

OSX

```
oliveagle ~ [16:10:32]
$ tar --help | grep xattrs
oliveagle ~ [16:47:14]
$ uname
Darwin
```

**Comment by wnemay** [comment]
Using homebrew on OSX, I install gnu-tar (the current version is 1.28)
I then updated the **utils.go** file (line 17) to use **gtar** instead of tar.
I did the same in the **export.go** file (line 532)

**Comment by oogali** [comment]
@jwilder So, I'm assuming one can't work around this in the OS X binary release, and has to build from source to implement the hack @wnemay mentioned?

**Comment by oogali** [comment]
Never mind, I see you just updated utils_darwin.go for this.

**Comment by mitsuh** [comment]
Quick and dirty workaround: brew install gnu-tar, then put a symlink tar -> gtar in your PATH before /usr/bin/tar.

**Comment by daluu** [comment]
@oogali this might work in the interim on Mac w/o recompiling source, according to tips on brew install of gnu-tar:

> gnu-tar has been installed as "gtar".

> If you really need to use it as "tar", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"

> Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:

    MANPATH="/usr/local/opt/gnu-tar/libexec/gnuman:$MANPATH"

**Comment by rpullm168** [comment]
Yes, even in the latest version, 'docker-squash' is still broken on macOS.  I'm sorry, requiring gnu tar for some particular command-line option you need in the implementation excludes an entire platform, which fits the definition of "broken".  Especially since installation of gnu tar on Mojave is a non-trivial exercise that I wouldn't want to document/repeat for all of our developers, and even after installed would then force every other tar-integrated app on the box to now use gnu tar instead of bsd tar.  (Any religious discussion of "well gnu tar is better anyway" or the like is off-topic -- replacement introduces potential compatibility issues with every such app that may assume/require bsd tar.)

If docker-squash truly can't live without gnu tar, then for the benefit of us poor saps stuck using macOS, at least do what you (erroneously elsewhere) said you do, and check explicitly for 'gtar' in the path before assuming 'tar' is gnu tar.  I regret the plaintive tone here, but that's a pretty basic functional omission with dire consequences (an entire platform unsupported) and an easy solution.
