### ISSUE TITLE
Error 1473, pushing a loaded docker image from a squashed tar file. 

### ISSUE THREAD

**Issue by arcolombo** [jwilder/docker-squash#31]
Hi.  First this software is great.  I was able to squash a very large image down to 10GB, and run the new docker image.
# Squash version

sudo docker-squash -v
v0.1.0

 the issue I am having is that after squashing the docker image, I can not pushed the new squashed image onto the docker hub.

For my example , I squashed my 40GB image into a file called squashed.tar.  then loaded the squashed.tar into  a new image called arcolombo/artemisunlayer:v1.   I can create containers successfully and everything looks great.
docker save <someimage> > aretemis.v156.squashed.tar
sudo docker-squash -i artemis.v156.squashed.tar -o squashed.tar -t arcolombo/artemisunlayer:v1
cat squashed.tar | docker load

anthonycolombo@quigonjinn:~/Documents$ ls
Artemis  artemis.v156.squashed.tar  squashed.tar
anthonycolombo@quigonjinn:~/Documents$ sudo docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
arcolombo/artemisunlayer   v1                  3b15a479aa85        31 minutes ago      10.21 GB
arcolombo/artemis          v156                de9bc789af1d        8 days ago          39.91 GB

when I run sudo docker push arcolombo/artemisunlayer:v1

the error is 

The push refers to a repository [arcolombo/artemisunlayer](len: 1)
3b15a479aa85: Image already exists 
f43a789562e2: Image already exists 
20895e1cb336: Image already exists 
8bf26c72ef69: Image already exists 
90e1f131e119: Image push failed 
FATA[1416] Error pushing to registry: Put https://registry-1.docker.io/v2/arcolombo/artemisunlayer/blobs/uploads/4accb54c-a964-4153-ac24-7a8610662ec0?_state=gx-cY2jt1fzbwLyOcnLYZKxt_e4-1cCJ8bK8WUvQwiV7Ik5hbWUiOiJhcmNvbG9tYm8vYXJ0ZW1pc3VubGF5ZXIiLCJVVUlEIjoiNGFjY2I1NGMtYTk2NC00MTUzLWFjMjQtN2E4NjEwNjYyZWMwIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTEyVDE4OjQ1OjQxLjAyMDAwNDg5N1oifQ%3D%3D&digest=sha256%3A1da5e7d6dc4f04d8038b88fe7fd4e726d71e24fc98f4095c711d63b67d760979: use of closed network connection 

I am using a wired network for ethernet ?  This sounds like a docker bug? but just looking for a confirm? 

thank you again for your great software

Anthony C.

anthonycolombo@quigonjinn:~/Documents$ sudo docker info
[sudo] password for anthonycolombo: 
Containers: 1
Images: 129
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 131
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-50-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.712 GiB
Name: quigonjinn
ID: U5LV:PN5L:LQZY:B36M:IJF7:LYRS:LEQB:2NMY:RNVY:IYYV:GWRI:YRBO
Username: arcolombo
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
anthonycolombo@quigonjinn:~/Documents$ sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

So I've tested the docker-squash on a very large image (40GB) and realized that perhaps maybe this error of push a docker squashed image was specific to my image.

I tested docker-squash on a test image that is very small , 4GB, and squashed it, and tried to then push the docker squashed loaded image, and generated the error.

anthonycolombo@quigonjinn:~/Documents/trnaDB$ sudo docker push arcolombo/newtag
The push refers to a repository [docker.io/arcolombo/newtag](len: 1)
378d25546ce5: Image successfully pushed 
dbddfc1d9325: Image successfully pushed 
7325be38363d: Pushing 2.997 GB/3.025 GB
EOF

Here are the commands use to generate this error

> sudo docker save 40f425f4e713 > image.tar
> sudo docker-squash -i image.tar -o mut.squashed.tar -t arcolombo/newtag
> cat mut.squashed.tar | sudo docker load
> sudo docker push arcolombo/newtag
> 
> anthonycolombo@quigonjinn:~/Documents/trnaDB$ sudo docker push arcolombo/newtag
> The push refers to a repository [docker.io/arcolombo/newtag](len: 1)
> 378d25546ce5: Image successfully pushed 
> dbddfc1d9325: Image successfully pushed 
> 7325be38363d: Pushing 2.997 GB/3.025 GB
> EOF

It appears that there is an unexpected EOF in the middle of these squashed layers.

**Comment by todd-alexion** [comment]
I am also getting an error trying to squash a 5.9 GB image.

The command: `docker save fcffd9463937 | sudo ./docker-squash -from root -t newtag | docker load`

The error (after several minutes of processing): `tar: This does not look like a tar archive`

**Comment by todd-alexion** [comment]
my command:  

`docker save fcffd9463937 | sudo ./docker-squash -from root -verbose | docker load`

The output:

> Loading export from STDIN using /tmp/docker-squash731940615 for tempdir
> Loaded image w/ 44 layers
Extracting layers...
  -  /tmp/docker-squash731940615/4c769e59972d110172e47c04430bb9cdaad8901851c5a95b2fefff398d675981/layer.tar
  -  /tmp/docker-squash731940615/799e2eee7fe9381840881b58250640ac418ad5d0301661e3351dcd2087e25519/layer.tar
  -  /tmp/docker-squash731940615/abc02187162ab43f0e8de3bc71934cac0809d4bc442c417cee42b0c45a5ba7b4/layer.tar
  -  /tmp/docker-squash731940615/b8ba9d82a57cf485085f6aa2e0f034ee1c22bb0e1372a3e5402b7fc91fde0e45/layer.tar
  -  /tmp/docker-squash731940615/d42b36e7d1eed2421a0823d422c47058d01d61bf88604c75c4545f8b92d93787/layer.tar
  -  /tmp/docker-squash731940615/d96a733457a250bf3426d278c1bb990a4b308f0b44b4aca5108d1961844f5468/layer.tar
  -  /tmp/docker-squash731940615/fda264c041e3aa78ae1466213ca249da44d14637ce09cecbf2ddcc52697bac28/layer.tar
  -  /tmp/docker-squash731940615/1c011745ff7b3fab56c3b1470b090239979c34a95ca9fe78b50d973ae4df72e6/layer.tar
  -  /tmp/docker-squash731940615/1836e55fa9c229874460103a2b8397c027528384013aebaba38749b37b2fe597/layer.tar
  -  /tmp/docker-squash731940615/35c8add16dd7e1519867aba6338a6a7ca240027873afd63adacf87f37d6b47d7/layer.tar
  -  /tmp/docker-squash731940615/5a34f9f2508461bd54d3298dfafb534263cb4781f66a9cd1a838c1db052ce213/layer.tar

> tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

> ERROR: exit status 2
> Removing tempdir /tmp/docker-squash731940615
invalid argument
